package eu.peppol;

import eu.peppol.identifier.*;

import java.util.Date;

/**
 * Our representation of the SBDH (Standard Business Document Header), which makes us
 * independent of the StandardBusinessDocumentHeader generated by JAXB. Furthermore
 * the UN/CEFACT SBDH is kind of awkward to use as some of the elements of interest to us, are
 * split into several fields.
 *
 * @author steinar
 *         Date: 04.11.13
 *         Time: 13:44
 */
public class PeppolStandardBusinessHeader {

    /**
     * Peppol Participant Identification for the recipient
     */
    private ParticipantId recipientId;
    /**
     * Peppol Participant Identification for the sender
     */
    private ParticipantId senderId;

    private PeppolDocumentTypeId peppolDocumentTypeId;
    private PeppolProcessTypeId profileTypeIdentifier;

    /** Represents the unique identity of a message, which is assigned upon creation of the envelope (SBDH).
     *
     * This messageId does not correspond to the "messageId", which should have been named "transmission id",
     * which is found in the START header.
     *
     * <code>//StandardBusinessDocumentHeader/DocumentIdentification/InstanceIdentifier</code>
     */
    private MessageId messageId;
    private Date creationDateAndTime;

    /**
     * Copy constructor
     *
     * @param sbdh
     */
    public PeppolStandardBusinessHeader(PeppolStandardBusinessHeader sbdh) {
        recipientId = sbdh.getRecipientId();
        senderId = sbdh.getSenderId();
        peppolDocumentTypeId = sbdh.getDocumentTypeIdentifier();
        profileTypeIdentifier = sbdh.getProfileTypeIdentifier();
        messageId = sbdh.getMessageId();
        creationDateAndTime = sbdh.getCreationDateAndTime();
    }

    public PeppolStandardBusinessHeader() {
    }

    public void setRecipientId(ParticipantId recipientId) {
        this.recipientId = recipientId;
    }

    public ParticipantId getRecipientId() {
        return recipientId;
    }

    public void setSenderId(ParticipantId senderId) {
        this.senderId = senderId;
    }

    public ParticipantId getSenderId() {
        return senderId;
    }

    public void setMessageId(MessageId messageId) {
        this.messageId = messageId;
    }

    public MessageId getMessageId() {
        return messageId;
    }

    public void setCreationDateAndTime(Date creationDateAndTime) {
        this.creationDateAndTime = creationDateAndTime;
    }

    public Date getCreationDateAndTime() {
        return creationDateAndTime;
    }

    public void setDocumentTypeIdentifier(PeppolDocumentTypeId documentTypeIdentifier) {
        this.peppolDocumentTypeId = documentTypeIdentifier;
    }

    public PeppolDocumentTypeId getDocumentTypeIdentifier() {
        return peppolDocumentTypeId;
    }

    public void setProfileTypeIdentifier(PeppolProcessTypeId profileTypeIdentifier) {
        this.profileTypeIdentifier = profileTypeIdentifier;
    }

    public PeppolProcessTypeId getProfileTypeIdentifier() {
        return profileTypeIdentifier;
    }
}
