name: Bug report
description: Create a bug report to help us improve
labels:
  - kind/bug
  - status/0-triage
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug...
        If this is a security issue please report it to the [oxalis@norstella.no](mailto:oxalis@norstella.no).
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please give a clear and concise description of the bug
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduce
      description: Please list steps to reproduce the bug
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What is the expected behavior?
      placeholder: |
        E.g. "...."
  - type: textarea
    id: Oxalis-version
    attributes:
      label: Oxalis version
      description: Mention Oxalis version
      render: bash
      placeholder: |
        E.g. "...."
    validations:
      required: true
  - type: textarea
    id: JDK-version
    attributes:
      label: JDK version
      description: JDK version where Oxalis is running
      render: bash
      placeholder: |
        E.g. "...."
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Info
      description: Additional info you want to provide such as logs, system info, environment, etc.
    validations:
      required: false