= Configuration

== Upgrading to 4.0

This is an overview of keys used for configuration when converting from Oxalis version 2.x/3.x to Oxalis version 4.x.

As of version 4.0 is the configuration file named ```oxalis.conf```.

[cols="3*",options="header"]
|===
| oxalis-globals.properties (pre 4.0)
| oxalis.conf (4.0+)
| Default value

3+h| _Database_

| oxalis.datasource.jndi.name
|
|

| oxalis.jdbc.driver.class
|
|

| oxalis.jdbc.class.path
|
|

| oxalis.jdbc.connection.uri
|
|

| oxalis.jdbc.dialect
|
|

| oxalis.jdbc.user
|
|

| oxalis.jdbc.password
|
|

| oxalis.jdbc.validation.query
|
|

3+h| _HTTP_

| oxalis.connection.timeout
| http.timeout.connect
| 5000

| oxalis.read.timeout
| http.timeout.read
| 5000

3+h| _Keystore_

| oxalis.keystore
| keystore.path
| oxalis-keystore.jks

| oxalis.keystore.password
| keystore.password
| changeit

| _New_
| keystore.key.alias
| ap

| _New_
| keystore.key.password
| changeit

3+h| _Logging_

| oxalis.app.log.config
| _Removed_
|

| oxalis.inbound.log.config
|
|

3+h| _Lookup_

| oxalis.sml.hostname
| _Removed_
| _Depending on mode_

3+h| _Mode_

| oxalis.operation.mode
| _Removed_
| _Detected using certificate_

3+h| _Proxy_

| oxalis.httpProxyHost
| _See link:#_proxy[Proxy]._
|

| oxalis.httpProxyPort
| _See link:#_proxy[Proxy]._
|

| oxalis.proxyUser
| _See link:#_proxy[Proxy]._
|

| oxalis.proxyPassword
| _See link:#_proxy[Proxy]._
|

3+h| _Storage_

| oxalis.inbound.message.store
|
|

| oxalis.persistence.class.path
|
|

3+h| _Truststore_

| oxalis.truststore.password
| _Removed_
|

|===

== HTTP clients

For outbound HTTP connections is link:https://hc.apache.org/[Apache HttpComponents] used.


=== Connection pool

Oxalis uses a shared connection pool of keep-alive connections to speed up transmission.

[source,conf]
.Default configuration
----
http.pool.max_route = 2
http.pool.total = 20
----

=== Proxy

Proxy is configured using link:#_java_properties[Java properties] as described in the link:https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html[Java 8 documentation].

.Some relevant properties
* java.net.useSystemProxies
* http.proxyHost
* http.proxyPort
* http.nonProxyHosts
* https.proxyHost
* https.proxyPort
* http.proxyUser
* http.proxyPassword

=== Timeouts

[source,conf]
.Default configuration
----
http.timeout.connect = 5000
http.timeout.read = 5000
----

== Java properties

It is recommended to set Java properties as part of running Oxalis - not having Oxalis set Java properties.

[source,concole]
.The recommended way of setting properties on command line.
----
java -Dhttp.proxyHost=10.0.0.50 -Dhttp.proxyPort=8080
----

In some situations may it be needed to put Java properties in the configuration file. Java propterties in the configuration file will be set just after configuration is loaded.

Properties are added by simple prefixing them with ```oxalis.java```.

[source,conf]
.Java properties in Oxalis configuration file.
----
oxalis.java.http.proxyHost = 10.0.0.50
oxalis.java.http.proxyPort = 80
----


== Key store

keystore.path::
Path to file containing key store.
keystore.password::
Password for key store.
keystore.key.alias::
Alias for key with certificate
keystore.key.password::
Password for key.

[source,conf]
.Default configuration
----
keystore.path = oxalis-keystore.jks
keystore.password = changeit
keystore.key.alias = ap
keystore.key.password = changeit
----
