name: Oxalis Master Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Allow SHA1 on Java 17
      run: |
        echo 'File java.security is found in /usr/lib/jvm subfolders:'
        find /usr/lib/jvm -type f -name "java.security"
        echo JAVA_HOME=${JAVA_HOME}
        export JAVA_SEC_FILE=${JAVA_HOME}/conf/security/java.security
        echo java.security path: ${JAVA_SEC_FILE}
        grep -F -v "http://www.w3.org/2000/09/xmldsig#sha1" ${JAVA_SEC_FILE} | \
          grep -F -v "http://www.w3.org/2000/09/xmldsig#rsa-sha1" > \
          ${JAVA_SEC_FILE}.fixed
        ls -la ${JAVA_SEC_FILE}*
        mv ${JAVA_SEC_FILE}.fixed ${JAVA_SEC_FILE}
        echo "Disallowed sha1 algorithms:"
        grep -F "sha1" ${JAVA_SEC_FILE}

    - name: Build with Maven
      run: mvn -B --no-transfer-progress  package --file pom.xml
