name: Oxalis Master Build

on: [push]

jobs:
  master-branch-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # run this job only for the master branch
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B --no-transfer-progress  package --file pom.xml

  milestone-6-branch-build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/feature/milestone-6' # run this job only for the feature/milestone-6 branch
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Maven
        run: mvn -B --no-transfer-progress  package --file pom.xml